
#__________________________________________________
# ./
# Sconscript
#__________________________________________________
# author        : colonel
# last modified : 2016/9/16
#__________________________________________________
#
# sub-compile script
#

#___________________________________________
# Import Environment from above-level script
#___________________________________________

Import('env')

def objectFromFiles(files):
    return [env.Object(file) for file in files]

#____________________________________
# debugIndependantGaussianRNG program
#____________________________________

target  = 'debugIndependantGaussianRNG'
main    = ['debugIndependantGaussianRNG.cpp']
sources = ['../utils/random/independantGaussianRNG.cpp']
libs    = []
libpath = []

debugIndependantGaussianRNG = env.Program(target = target,
        source  = main + objectFromFiles(sources),
        LIBS    = libs,
        LIBPATH = libpath)

#______________________
# debugLorenz63 program
#______________________

target  = 'debugLorenz63'
main    = ['debugLorenz63.cpp']
sources = ['../utils/random/independantGaussianRNG.cpp',
        '../utils/vector/vectorOperations.cpp',
        '../integration/eulerExplScheme.cpp',
        '../integration/rk2scheme.cpp',
        '../integration/rk4scheme.cpp',
        '../model/lorenz63.cpp']
libs    = []
libpath = []

debugLorenz63 = env.Program(target = target,
        source  = main + objectFromFiles(sources),
        LIBS    = libs,
        LIBPATH = libpath)

